version: '3.8'
services:
  dev-db:
    image: postgres:13.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest
    ports:
      - 5434:5432
    networks:
      - tuto-nest
  test-db:
    image: postgres:13.2
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest
    networks:
      - tuto-nest
networks:
  tuto-nest: